services:
  etopa:
    image: ltheinrich/etopa:latest
    container_name: etopa
    restart: always
    ports:
     - 127.0.0.1:8080:80
     - 127.0.0.1:8443:443
     - 127.0.0.1:4490:4490
    volumes:
      - ./etopa/:/etopa/
