[package]
name = "etopa"
version = "0.0.0"
authors = ["Lennart Heinrich <lennart@ltheinrich.de>"]
edition = "2021"
rust-version = "1.56"
license = "ISC"
repository = "https://ltheinrich.de/etopa"
description = "Time-based one-time password authenticator"
homepage = "https://etopa.de"

[dependencies]
kern = "1.5.1"
aes-gcm = "0.10.1"
ring = "0.16.20"
sha3 = "0.10.6"
hex = "0.4.3"
rust-argon2 = "1.0.0"
base32 = "0.4.0"
rand = "0.8.5"
