[package]
name = "etopa"
version = "0.0.0"
authors = ["Lennart Heinrich <lennart@ltheinrich.de>"]
edition = "2018"
license = "ISC"
repository = "https://ltheinrich.de/etopa"
description = "Time-based one-time password authenticator"
homepage = "https://etopa.de"

[dependencies]
kern = "1.2.3"
aes-gcm = "0.8.0"
ring = "0.16.19"
sha3 = "0.9.1"
hex = "0.4.2"
rust-argon2 = "0.8.3"
base32 = "0.4.0"
rand = { version = "0.8.0", features = ["getrandom"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2.69", features = ["serde-serialize"] }
getrandom = {version = "0.2.0", features = ["js"] }
