[package]
name = "etopa"
version = "0.0.1-beta.0"
authors = ["Lennart Heinrich <lennart@ltheinrich.de>"]
edition = "2018"
license = "ISC"
repository = "https://github.com/ltheinrich/etopa"
description = "Time-based one-time password authenticator"
homepage = "https://etopa.de"

[dependencies]
kern = "1.1.6"
aes-gcm = "0.5.0"
rand = "0.7.3"
ring = "0.16.13"
data-encoding = "2.2.0"
sha3 = "0.8.2"
hex = "0.4.2"
rust-argon2 = "=0.8.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2.62", features = ["serde-serialize"] }
rand = { version = "0.7.3", features = ["wasm-bindgen"] }
