[package]
name = "etopaw"
version = "0.0.0"
authors = ["Lennart Heinrich <lennart@ltheinrich.de>"]
edition = "2018"
license = "ISC"
repository = "https://ltheinrich.de/etopa"
description = "Etopa for Web"
homepage = "https://etopa.de"

[dependencies]
etopa = { path = "../etopa" }
console_error_panic_hook = "0.1.6"
wee_alloc = "0.4.5"
serde = "1.0.123"
serde_derive = "1.0.122"

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = false #["-Oz", "--enable-mutable-globals"]
