[package]
name = "etopai"
version = "0.0.1-beta.0"
authors = ["Lennart Heinrich <lennart@ltheinrich.de>"]
edition = "2018"
license = "ISC"
repository = "https://github.com/ltheinrich/etopa"
description = "Etopa HTTPS API"
homepage = "https://etopa.de"

[dependencies]
etopa = { path = "../etopa" }
lhi = "=0.0.0-dev.14" # 0.0.0 is outdated
json = "0.12.4"
