[package]
name = "etopai"
version = "0.0.5"
authors = ["Lennart Heinrich <lennart@ltheinrich.de>"]
edition = "2018"
license = "ISC"
repository = "https://github.com/ltheinrich/etopa"
description = "Etopa HTTPS API"
homepage = "https://etopa.de"

[dependencies]
etopa = { path = "../etopa" }
kern = { version = "1.2.0", features = ["http"] }
json = "0.12.4"
