[package]
name = "etopan"
version = "0.0.4"
authors = ["Lennart Heinrich <lennart@ltheinrich.de>"]
edition = "2018"
license = "ISC"
repository = "https://github.com/ltheinrich/etopa"
description = "Etopa for Android"
homepage = "https://etopa.de"

[dependencies]
etopa = { path = "../etopa" }
jni = { version = "0.18.0", default-features = false }

[lib]
name = "etopan"
crate-type = ["cdylib"]
