name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cargo Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Check
        run: make check

      - name: Notice
        run: if ! [ $(wc -l < NOTICE.txt) -gt 860 ]; then exit 1; fi

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Android Cache
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/lib/android/sdk
          key: ${{ runner.os }}-configure-cache

      - name: Cargo Cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"

      - name: Configure
        env:
          ANDROID_SDK_MANAGER: /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager
        run: |
          ./configure

      - name: Make
        env:
          DEBUG_SIGN: y
          NDK_TOOLCHAIN_BIN: /usr/local/lib/android/sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin
        run: |
          make noclean
