name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cargo Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Format
        run: cargo fmt --all --verbose -- --check

      - name: Check
        run: make check

      - name: Notice
        run: if ! [ $(wc -l < NOTICE.txt) -gt 860 ]; then exit 1; fi

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Cache
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.ANDROID_HOME }}
            /usr/share/rust/.cargo
          key: ${{ runner.os }}-configure-cache

      - name: Cargo Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Configure
        env:
          ANDROID_SDK_MANAGER: /usr/local/lib/android/sdk/tools/bin/sdkmanager
        run: |
          ./configure

      - name: Make
        env:
          DEBUG_SIGN: y
          NDK_BIN_PATH: /usr/local/lib/android/sdk/ndk/22.1.7171670
          NDK_TOOLCHAIN_BIN: /usr/local/lib/android/sdk/ndk/22.1.7171670/toolchains/llvm/prebuilt/linux-x86_64/bin
        run: |
          make
