name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cargo Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Check
        run: make check

      - name: Notice
        run: if ! [ $(wc -l < NOTICE.txt) -gt 860 ]; then exit 1; fi

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configure Cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.ANDROID_HOME }}
            /usr/share/rust/.cargo
          key: ${{ runner.os }}-configure-cache

      - name: Cargo Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Configure
        env:
          ANDROID_SDK_MANAGER: /usr/local/lib/android/sdk/tools/bin/sdkmanager
        run: |
          ./configure
          find -L /usr/local/lib/android/sdk/ndk/24.0.8215888 -name libunwind.a -execdir sh -c 'echo "INPUT(-lunwind)" > libgcc.a' \;

      - name: Make
        env:
          DEBUG_SIGN: y
          NDK_TOOLCHAIN_BIN: /usr/local/lib/android/sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/linux-x86_64/bin
        run: |
          make noclean
